### ISSUE TITLE
[Mentorship Session Request][Data Science]  Data Science Enthusiasts

### ISSUE THREAD

**Issue by veereshbv04** [tanaypratap/mentorship-karona#11]
# Student Group Name
Data science enthusiasts

## What do you want the speaker to talk about?
Making Career in Data Science

## Any additional comments?
most of us are 2nd year computer science students,I request the speaker to guide us in the path to get placed in Companies in data Science team 

## Will this session be recorded?
yes

## Where are you going to publish the recording?
youtube

## What will be the attendance?
atleast 10 students will attend this

## Preferred Timing?
12-04-2020,  sunday, 3pm or 8pm

## Your Name and Contact Details
Veeresh B V
veereshbv04@gmail.com
https://www.linkedin.com/in/veeresh-b-v-789a61174/
9731970140

**Comment by tanaypratap** [comment]
@ajinkyakolhe112 would you be interested in taking this session?

**Comment by veereshbv04** [comment]
Yes, I am very much interested in attending this session.



Thanks and Regards
Veeresh B V
