### ISSUE TITLE
[Mentorship Session Request][Web Development, Mobile App Development, User Interface] Academy of Technology, Adisaptagram

### ISSUE THREAD

**Issue by jasbindar-singh** [tanaypratap/mentorship-karona#17]
# Student Group Name
Development Ninjas
## What do you want the speaker to talk about?
To talk about different frontend frameworks, web development, cross-platform mobile app development, share his insight about the industry standards, and how can we aim for better companies, how things are going to change after this pandemic, and how to deal with the current employability situation, some project or stories if the speaker wants to share with us and about how things are going in life right now.
## Are you looking for a specific tech stack expert? If yes, mention
We want to talk about UI, frontend web frameworks, cross-platform mobile development.
## Any additional comments?
We are totally comfortable if the speaker wants to talk about something other than the topics mentioned.
## Will this session be recorded?
Yes, we can, we could screen record the whole session.
## Where are you going to publish the recording?
If recorded we can publish it on youtube, and we could also share screenshots and posts on LinkedIn.
## What will be the attendance?
The attendance will be around 9 people.
## Preferred Timing?
We could do it in the evenings this weekend or the time that the speaker is comfortable with.
## Your Name and Contact Details
Name: Jasbindar Singh
LinkedIn: https://www.linkedin.com/in/singhjs/
Phone: 9804628251
Email: jasbindar1998@gmail.com

**Comment by chirgjn** [comment]
I can take this.
Preferred time: Sunday, 12th April 2020, 6 PM IST

**Comment by tanaypratap** [comment]
@jasbindar-singh please work with @chirgjn to conduct the session. 

Once done, close this issue with the session details.

**Comment by jasbindar-singh** [comment]
Hi, @chirgjn thank you for the consideration and I have sent you a request on LinkedIn for communication.
And thanks @tanaypratap for starting out this mentorship program and helping us.
