### ISSUE TITLE
[Mentorship Session Request][Open Source Development] Fractal, IET Lucknow

### ISSUE THREAD

**Issue by singhv1shal** [tanaypratap/mentorship-karona#20]
# Student Group Name
Fractal, IET Lucknow
We are coding club of Institute of Engineering and Technology Lucknow.

## What do you want the speaker to talk about?

Why a student should do Open Source? 

A generalized approach to kickstart in Open Source Development. 

How it can help in building a good profile for - 1. Student 2. Professionals.

What are some good platforms to start practice?

How to contribute to big open-source projects -just for example django,linux,firefox.

## Are you looking for a specific tech stack expert? If yes, mention

Since open source is diverse we would love to have a mentor to guide about overview and applicable to all domains.

## Will this session be recorded?

Can be a live session with hands-on with QnAs as well and can also record the session.

## Where are you going to publish the recording?

We will publish the recording on youtube and update details of event on our LinkedIn, Facebook pages.

## What will be the attendance?

70-100

## Preferred Timing?

15:00 hrs. or based on mentor preference.

## Your Name and Contact Details

Vishal Singh

[Linked In](https://www.linkedin.com/in/vishal-singh-48844015a)
Mail- singhvishal0304@gmail.com
Contact: +91 7007110758

**Comment by ameerjhan** [comment]
Hi @singhv1shal,

I have been doing open source for a very long time and I love it a lot.
I maintain the popular repo https://github.com/twobin/react-lazyload and have built few OSS which have around 250 stars and I would love to share the experience and learning I had during this journey with you all :)

**Comment by ameerthehacker** [comment]
Hi @singhv1shal,

I have been doing open source for a very long time and I love it a lot.
I maintain the popular repo https://github.com/twobin/react-lazyload and have built few OSS which have around 250 stars and I would love to share the experience and learning I had during this journey with you all :)

**Comment by singhv1shal** [comment]
Hello @ameerthehacker ,
We will really be pleased to have session with you. Please let us know your preferred dates for the same. Can you please share your contact details so that i can connect with you. 
Thanks for the opportunity. We are looking forward for a productive and useful session session with you.

**Comment by ameerthehacker** [comment]
@singhv1shal anytime after 7 PM during weekdays and after 10 AM during weekends would work for me. Please feel free to call me 9566602688 😄 to discuss further

**Comment by tanaypratap** [comment]
If you have got a mentor for your session please consider closing the issue. :)

**Comment by gkanishk** [comment]
Hey, @singhv1shal kindly mention the event details once finalized.

**Comment by singhv1shal** [comment]
Sure, I will update the finalized details here and linkedin as well by today. Thanks

**Comment by singhv1shal** [comment]
We have discussed with our team and students. We found 18 April (Saturday) as the suitable date for the session. We can plan the event at 15:00 hrs. @ameerthehacker Please let us know if this schedule is comfortable for you. Thanks

**Comment by gkanishk** [comment]
@singhv1shal just raise a **PR** inside [Events.md](https://github.com/tanaypratap/mentorship-karona/blob/master/EVENTS.md) file with the event details once finalized.

**Comment by ameerthehacker** [comment]
@singhv1shal sounds good to me!

**Comment by vinitshahdeo** [comment]
All the best @ameerthehacker. 💯 ✌️
Nail it! 🔥

**Comment by ameerthehacker** [comment]
@vinitshahdeo thanks buddy 🤗
