### ISSUE TITLE
[Mentorship Session Request][ <Fullstack WebDevelopment> ] <JSS Academy of Technical Education Noida>

### ISSUE THREAD

**Issue by ayushpaharia** [tanaypratap/mentorship-karona#32]
# Student Group Name
Freelance Web Developers
## What do you want the speaker to talk about?
To help us understand the lifecycle of a web product. Popular apps and how they were created. Full stack roadmap. Tech Stack.
## Are you looking for a specific tech stack expert? If yes, mention
Full stack knowledge with working of cloud deployment
## Will this session be recorded?
Yes, Most Likely
## Where are you going to publish the recording?
I will share it among my peers or further on youtube for people to learn
## What will be the attendance?
10+
## Preferred Timing?
Weekday 2:00PM onward, Weekend ( Sunday )( anytime ), Preference of mentor
## Mentor suggestion?(_have a look at mentor's list and then suggest_)
Any skilled expert with great knowledge in Fullstack experience in working with web products.
## Your Name and Contact Details
Ayush Paharia , 8826557335, https://linkedin.com/in/ayushcodes1812

**Comment by tanaypratap** [comment]
@ayushpaharia I would suggest that you make a separate request for ML/Data Science and edit this issue to be only Web development.

**Comment by vinitshahdeo** [comment]
Hello @ayushpaharia,

I'd love to take a session on **Full Stack Development**. I'm available on weekends. Please share further details here.

> **PS: Feel free to ping me on [LinkedIn](https://www.linkedin.com/in/vinitshahdeo/) / [Twitter](https://twitter.com/Vinit_Shahdeo). Learn more<sup>[click here](https://fayz.in/stories/s/1522/0/?ckt_id=ZGL1ZGVk)</sup>.**
