### ISSUE TITLE
[Mentorship Session Request][ Community  ] Script Foundation

### ISSUE THREAD

**Issue by jaisadana1999** [tanaypratap/mentorship-karona#45]
# Script Foundation

## Your Name and Contact Details
Jai Sadana
7011723246

**Comment by tanaypratap** [comment]
Jai,

We'll find out speakers for you but you can you first edit the issue and
not make everything a heading. Please reference other open issues for
formatting.

Markdown is real. Learn it. Use it.

./Tanay
I am a mentor for college grads. if you or someone you know wants to learn
JS, or get a job. Check out learncodingfree.org and jobChallenge.dev
