### ISSUE TITLE
[Mentorship Session Request][ Competitive programming ] <Coding Club , IIITV>

### ISSUE THREAD

**Issue by anujpuri72** [tanaypratap/mentorship-karona#47]
# Student Group Name
 Coding Club, IIITV

## What do you want the speaker to talk about?
How to master Competitive programming and 
how it is one of the major factor in getting jobs in major tech companies. 

## Will this session be recorded?
Yes, the meeting will be recorded and be saved on google drive so that if anyone who is interested in attending the event but can't attend it due to any reason may refer to it in future.

## Where are you going to publish the recording?
All IIITV coding club handles( G-dri e,Twitter,Facebook,Linked in etc)

## What will be the attendance?
30-35,but I can assure you a minimum of 25 participants

## Preferred Timing?
As per mentor's choice

## Your Name and Contact Details
Anuj Puri
email-anujpuri72@gmail.com
C.no-7889561310

**Comment by zacker-222** [comment]
Hey @anujpuri72 
I would love to take a session on competitive Programming.

**Comment by anujpuri72** [comment]
Sure sir, Let me know your availability so we can plan the event.

**Comment by zacker-222** [comment]
I am available on weekends after 4 PM. Also it would be great if you could decide specific topics that you want to be covered during the session.

**Comment by anujpuri72** [comment]
@tanaypratap These  sessions were  held on 16th and 17th May

**Comment by gkanishk** [comment]
@anujpuri72 can you add the details of event inside `events.md` file

**Comment by anujpuri72** [comment]
@gkanishk  Done Sir
